spring:
  redis:
    # 服务器地址
    host: 122.51.57.9
    # 服务器端口
    port: 6379
    # 数据库索引(默认为0)
    database: 0
    # 连接密码(默认为空)
    password: jx1910
    lettuce:
      pool:
        # 最大空闲连接
        max-idle: 10
        # 最大连接数(使用负值表示没有限制)
        max-active: 10
        # 最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间(使用负值表示没有限制，一定要带单位)
        max-wait: 10000ms
    # 连接超时时间(毫秒，默认时2000ms，一定到带单位)
    timeout: 2000ms