spring:
  # 配置网页模板
  thymeleaf:
    # 传输类型：html
    servlet:
      content-type: text/html
    # 模板存在与resources/templates文件中
    prefix: classpath:/templates/
    # 模板文件后缀
    suffix: .html
    # 模板类型：HTML5
    mode: HTML5
    # 模板编码：UTF-8
    encoding: UTF-8
    # 不对模板进行缓存
    cache: false